# translational 
kp_x: 0.
kp_y: 0.
kp_z: 0.
#-----
ki_x: 0
ki_y: 0
ki_z: 0.
#-----
kd_x: 0.
kd_y: 0.
kd_z: 0.
#-----

# rotational 
kp_phi: 0.5
kp_theta: 0.5
kp_psi: 0.5
#-----
ki_phi: 0.5
ki_theta: 0.5
ki_psi: 0.5
#-----
kd_p: 0.5
kd_q: 0.5
kd_r: 0.5